In [42]:
# Importing pandas library
import pandas as pd
import numpy as np

# Creating a time series DataFrame with NaN values
dates = pd.date_range('2023-01-01', periods=6)
temperature_data = pd.DataFrame({
    'Temperature': [25.3, np.nan, np.nan, 24.1, 23.8, np.nan]
}, index=dates)

# Display the original DataFrame
print("Original Temperature Data:")
print(temperature_data)

# Forward fill (using previous valid observation)
ffill_temp = temperature_data.ffill()

# Display the result
print("\nTemperature Data after forward fill:")
print(ffill_temp)

# Limiting the number of consecutive fills
limited_ffill = temperature_data.ffill(limit=1)

# Display the result with limit
print("\nTemperature Data with limited forward fill (limit=1):")
print(limited_ffill)

Original Temperature Data:
            Temperature
2023-01-01         25.3
2023-01-02          NaN
2023-01-03          NaN
2023-01-04         24.1
2023-01-05         23.8
2023-01-06          NaN

Temperature Data after forward fill:
            Temperature
2023-01-01         25.3
2023-01-02         25.3
2023-01-03         25.3
2023-01-04         24.1
2023-01-05         23.8
2023-01-06         23.8

Temperature Data with limited forward fill (limit=1):
            Temperature
2023-01-01         25.3
2023-01-02         25.3
2023-01-03          NaN
2023-01-04         24.1
2023-01-05         23.8
2023-01-06         23.8

In [43]:
import pandas as pd
import numpy as np

In [44]:
# Create the dataset as a dictionary
data = {
    'Date': ['08-01', '08-02', '08-03', '08-04', '08-05', '08-06', '08-07', '08-08', '08-09', '08-10',
             '08-11', '08-12', '08-13', '08-14', '08-15', '08-16', '08-17', '08-18', '08-19', '08-20'],
    'Weekday': [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5],
    'Holiday': [0.0, 0.0, 0.0, 0.0, np.nan, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, np.nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'Temp': [25.1, 26.4, np.nan, 24.1, 24.7, 26.5, 27.6, 28.2, 27.1, 26.7, np.nan, 24.3, 23.1, 22.4, np.nan, 26.5, 28.6, np.nan, 27.0, 26.9],
    'Humidity': [99.0, np.nan, 96.0, 68.0, 98.0, 98.0, 78.0, np.nan, 70.0, 75.0, np.nan, 77.0, 77.0, 89.0, 80.0, 88.0, 76.0, np.nan, 73.0, 73.0],
    'Wind': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, np.nan, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, np.nan, 1.0, 0.0],
    'Outlook': ['rainy', 'sunny', 'rainy', 'overcast', 'rainy', np.nan, 'rainy', 'rainy', 'overcast', 'sunny', np.nan, 'overcast', 'sunny', 'rainy', 'sunny', 'rainy', np.nan, 'rainy', 'overcast', 'sunny'],
    'Crowdedness': [0.14, np.nan, 0.21, 0.68, 0.20, 0.32, 0.72, 0.61, np.nan, 0.54, np.nan, 0.67, 0.66, 0.38, 0.46, np.nan, 0.52, np.nan, 0.62, 0.81]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

In [45]:
# Display basic information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         20 non-null     str
 1   Weekday      20 non-null     int64
 2   Holiday      18 non-null     float64
 3   Temp         16 non-null     float64
 4   Humidity     16 non-null     float64
 5   Wind         18 non-null     float64
 6   Outlook      17 non-null     str
 7   Crowdedness  15 non-null     float64
dtypes: float64(5), int64(1), str(2)
memory usage: 1.4 KB

In [46]:
# Display the first few rows of the dataset
df.head()

    Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0  08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1  08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2  08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3  08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4  08-05        4      NaN  24.7      98.0   0.0     rainy         0.20

In [47]:
# Display the count of missing values in each column
df.isnull().sum()

Date           0
Weekday        0
Holiday        2
Temp           4
Humidity       4
Wind           2
Outlook        3
Crowdedness    5
dtype: int64

In [48]:
# Count missing values in each row
missing_count = df.isnull().sum(axis=1)
missing_count

0     0
1     2
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    4
11    1
12    0
13    0
14    1
15    1
16    1
17    4
18    0
19    0
dtype: int64

In [49]:
df

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1      99.0   0.0     rainy         0.14
1   08-02        1      0.0  26.4       NaN   0.0     sunny          NaN
2   08-03        2      0.0   NaN      96.0   0.0     rainy         0.21
3   08-04        3      0.0  24.1      68.0   0.0  overcast         0.68
4   08-05        4      NaN  24.7      98.0   0.0     rainy         0.20
5   08-06        5      0.0  26.5      98.0   0.0       NaN         0.32
6   08-07        6      0.0  27.6      78.0   0.0     rainy         0.72
7   08-08        0      0.0  28.2       NaN   0.0     rainy         0.61
8   08-09        1      0.0  27.1      70.0   0.0  overcast          NaN
9   08-10        2      1.0  26.7      75.0   NaN     sunny         0.54
10  08-11        3      0.0   NaN       NaN   0.0       NaN          NaN
11  08-12        4      NaN  24.3      77.0   0.0  overcast         0.67
12  08-13        5      0.0  23.1      77.0   1.0     sunny         0.66
13  08-14        6      0.0  22.4      89.0   1.0     rainy         0.38
14  08-15        0      0.0   NaN      80.0   1.0     sunny         0.46
15  08-16        1      0.0  26.5      88.0   1.0     rainy          NaN
16  08-17        2      0.0  28.6      76.0   0.0       NaN         0.52
17  08-18        3      0.0   NaN       NaN   NaN     rainy          NaN
18  08-19        4      0.0  27.0      73.0   1.0  overcast         0.62
19  08-20        5      0.0  26.9      73.0   0.0     sunny         0.81

In [50]:
# Count missing values in each row
missing_count = df.isnull().sum(axis=1)
missing_count

0     0
1     2
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    4
11    1
12    0
13    0
14    1
15    1
16    1
17    4
18    0
19    0
dtype: int64

In [51]:
# Keep only rows with less than 4 missing values
df_clean = df[missing_count < 4].copy()
df_clean.shape
# We’ve removed 2 rows that had too many missing values

(18, 8)

In [52]:
# Mean imputation for Humidity
df_clean['Humidity'] = df_clean['Humidity'].fillna(df_clean['Humidity'].mean())
df_clean

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1   99.0000   0.0     rainy         0.14
1   08-02        1      0.0  26.4   82.1875   0.0     sunny          NaN
2   08-03        2      0.0   NaN   96.0000   0.0     rainy         0.21
3   08-04        3      0.0  24.1   68.0000   0.0  overcast         0.68
4   08-05        4      NaN  24.7   98.0000   0.0     rainy         0.20
5   08-06        5      0.0  26.5   98.0000   0.0       NaN         0.32
6   08-07        6      0.0  27.6   78.0000   0.0     rainy         0.72
7   08-08        0      0.0  28.2   82.1875   0.0     rainy         0.61
8   08-09        1      0.0  27.1   70.0000   0.0  overcast          NaN
9   08-10        2      1.0  26.7   75.0000   NaN     sunny         0.54
11  08-12        4      NaN  24.3   77.0000   0.0  overcast         0.67
12  08-13        5      0.0  23.1   77.0000   1.0     sunny         0.66
13  08-14        6      0.0  22.4   89.0000   1.0     rainy         0.38
14  08-15        0      0.0   NaN   80.0000   1.0     sunny         0.46
15  08-16        1      0.0  26.5   88.0000   1.0     rainy          NaN
16  08-17        2      0.0  28.6   76.0000   0.0       NaN         0.52
18  08-19        4      0.0  27.0   73.0000   1.0  overcast         0.62
19  08-20        5      0.0  26.9   73.0000   0.0     sunny         0.81

1. Güncel Pandas'ta Olası bir "FutureWarning"

Pandas'ın yeni sürümlerinde, bu tarz zincirleme atama (df['col'] = df['col'].fillna(...)) bazen bir uyarı (FutureWarning / ChainedAssignmentError) verebiliyor, özellikle df_clean bir orijinal DataFrame'in kopyası/dilimi ise. Bunu önlemek için:

df_clean = df_clean.copy()  # en başta, eğer df_clean başka bir df'ten türetildiyse

In [53]:

# Mode imputation for Holiday
df_clean['Holiday'] = df_clean['Holiday'].fillna(df_clean['Holiday'].mode()[0])
df_clean

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1   99.0000   0.0     rainy         0.14
1   08-02        1      0.0  26.4   82.1875   0.0     sunny          NaN
2   08-03        2      0.0   NaN   96.0000   0.0     rainy         0.21
3   08-04        3      0.0  24.1   68.0000   0.0  overcast         0.68
4   08-05        4      0.0  24.7   98.0000   0.0     rainy         0.20
5   08-06        5      0.0  26.5   98.0000   0.0       NaN         0.32
6   08-07        6      0.0  27.6   78.0000   0.0     rainy         0.72
7   08-08        0      0.0  28.2   82.1875   0.0     rainy         0.61
8   08-09        1      0.0  27.1   70.0000   0.0  overcast          NaN
9   08-10        2      1.0  26.7   75.0000   NaN     sunny         0.54
11  08-12        4      0.0  24.3   77.0000   0.0  overcast         0.67
12  08-13        5      0.0  23.1   77.0000   1.0     sunny         0.66
13  08-14        6      0.0  22.4   89.0000   1.0     rainy         0.38
14  08-15        0      0.0   NaN   80.0000   1.0     sunny         0.46
15  08-16        1      0.0  26.5   88.0000   1.0     rainy          NaN
16  08-17        2      0.0  28.6   76.0000   0.0       NaN         0.52
18  08-19        4      0.0  27.0   73.0000   1.0  overcast         0.62
19  08-20        5      0.0  26.9   73.0000   0.0     sunny         0.81

2. Aynı İşlemi Tek Satırda Toplu Yapma (Okunabilirlik için)

df_clean = df_clean.fillna({

    'Humidity': df_clean['Humidity'].mean(),
    
    'Holiday': df_clean['Holiday'].mode()[0]
})

Bu, iki ayrı satır yerine tek bir fillna() çağrısında her sütuna kendi değerini atıyor, biraz daha derli toplu duruyor. Fonksiyonel olarak sizin kodunuzla birebir aynı sonucu verir, sadece stil tercihi.

3. Doldurmadan Önce Kontrol (Önerilir, Zorunlu Değil)

Az önce konuştuğumuz "mod her zaman doğru mu" tartışmasını hatırlarsak, Holiday için doldurmadan önce bir kontrol atmak iyi bir alışkanlık olur:

print(df_clean['Holiday'].value_counts())  # mod gerçekten baskın mı, yoksa 50-50'ye yakın mı?

Eğer Holiday sütununda 0 ve 1 sayıları birbirine çok yakınsa (örneğin 11 vs 9), mode imputation çok da güvenilir olmayabilir, böyle bir durumda Weekday'e göre koşullu mod (daha önce bahsettiğim groupby yöntemi) düşünülebilir.

4. Doldurma Sonrası Doğrulama

print(df_clean[['Humidity', 'Holiday']].isnull().sum())  # ikisi de 0 çıkmalı

In [54]:
df_clean

     Date  Weekday  Holiday  Temp  Humidity  Wind   Outlook  Crowdedness
0   08-01        0      0.0  25.1   99.0000   0.0     rainy         0.14
1   08-02        1      0.0  26.4   82.1875   0.0     sunny          NaN
2   08-03        2      0.0   NaN   96.0000   0.0     rainy         0.21
3   08-04        3      0.0  24.1   68.0000   0.0  overcast         0.68
4   08-05        4      0.0  24.7   98.0000   0.0     rainy         0.20
5   08-06        5      0.0  26.5   98.0000   0.0       NaN         0.32
6   08-07        6      0.0  27.6   78.0000   0.0     rainy         0.72
7   08-08        0      0.0  28.2   82.1875   0.0     rainy         0.61
8   08-09        1      0.0  27.1   70.0000   0.0  overcast          NaN
9   08-10        2      1.0  26.7   75.0000   NaN     sunny         0.54
11  08-12        4      0.0  24.3   77.0000   0.0  overcast         0.67
12  08-13        5      0.0  23.1   77.0000   1.0     sunny         0.66
13  08-14        6      0.0  22.4   89.0000   1.0     rainy         0.38
14  08-15        0      0.0   NaN   80.0000   1.0     sunny         0.46
15  08-16        1      0.0  26.5   88.0000   1.0     rainy          NaN
16  08-17        2      0.0  28.6   76.0000   0.0       NaN         0.52
18  08-19        4      0.0  27.0   73.0000   1.0  overcast         0.62
19  08-20        5      0.0  26.9   73.0000   0.0     sunny         0.81

In [55]:
df_clean['Temp'] = df_clean['Temp'].interpolate(method='linear')

In [57]:
df_clean['Outlook'] = df_clean['Outlook'].ffill().bfill()

In [58]:
df_clean['Wind'] = df_clean['Wind'].fillna(-1)

In [60]:
from sklearn.impute import KNNImputer

# One-hot encode the 'Outlook' column
outlook_encoded = pd.get_dummies(df_clean['Outlook'], prefix='Outlook')

# Prepare features for KNN imputation
features_for_knn = ['Weekday', 'Holiday', 'Temp', 'Humidity', 'Wind']
knn_features = pd.concat([df_clean[features_for_knn], outlook_encoded], axis=1)

# Apply KNN imputation
knn_imputer = KNNImputer(n_neighbors=3)
df_imputed = pd.DataFrame(knn_imputer.fit_transform(pd.concat([knn_features, df_clean[['Crowdedness']]], axis=1)),
                          columns=list(knn_features.columns) + ['Crowdedness'])

# Update the original dataframe with the imputed Crowdedness values
df_clean['Crowdedness'] = df_imputed['Crowdedness']

# KNN Imputer

In [61]:
from sklearn.impute import KNNImputer

In [62]:
# Sample dataset with missing values
data = {
    'Feature1': [1.0, 2.0, np.nan, 4.0],
    'Feature2': [np.nan, 2.0, 3.0, 4.0],
    'Feature3': [1.0, 2.0, 3.0, np.nan]
}
df = pd.DataFrame(data)

# Initialize KNNImputer
imputer = KNNImputer(n_neighbors=2)

# Impute missing values
df_imputed = imputer.fit_transform(df)

print("Data after KNN Imputation:\n", df_imputed)

Data after KNN Imputation:
 [[1.  2.5 1. ]
 [2.  2.  2. ]
 [3.  3.  3. ]
 [4.  4.  2.5]]

Missing Value Indicator

In [70]:
import pandas as pd
import numpy as np

# Sample DataFrame
data = {'ID': [1, 2, 3, 4, 5],
        'Age': [25, 30, np.nan, 35, np.nan],
        'Income': [50000, 60000, 75000, np.nan, 90000],
        'Score': [85, 90, 78, 92, 88]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

Original DataFrame:
   ID   Age   Income  Score
0   1  25.0  50000.0     85
1   2  30.0  60000.0     90
2   3   NaN  75000.0     78
3   4  35.0      NaN     92
4   5   NaN  90000.0     88

In [71]:
df

   ID   Age   Income  Score
0   1  25.0  50000.0     85
1   2  30.0  60000.0     90
2   3   NaN  75000.0     78
3   4  35.0      NaN     92
4   5   NaN  90000.0     88

In [74]:
df.isnull().any()

ID        False
Age        True
Income     True
Score     False
dtype: bool

In [76]:
df.columns[df.isnull().any()]

Index(['Age', 'Income'], dtype='str')

In [77]:
# Identify columns with missing values
cols_with_na = df.columns[df.isnull().any()].tolist()

In [79]:
# Create indicator features
for col in cols_with_na:
    df[col + '_missing_indicator'] = df[col].isnull().astype(int)

print("\nDataFrame with Missing Value Indicators:")
print(df)

DataFrame with Missing Value Indicators:
   ID   Age   Income  Score  Age_missing_indicator  Income_missing_indicator
0   1  25.0  50000.0     85                      0                         0
1   2  30.0  60000.0     90                      0                         0
2   3   NaN  75000.0     78                      1                         0
3   4  35.0      NaN     92                      0                         1
4   5   NaN  90000.0     88                      1                         0

In [80]:
from sklearn.impute import SimpleImputer

# Assume df is the DataFrame after adding indicators
# Impute missing values in the original 'Age' column using the median
median_imputer_age = SimpleImputer(strategy='median')
df['Age'] = median_imputer_age.fit_transform(df[['Age']])

# Impute missing values in the original 'Income' column using the mean
mean_imputer_income = SimpleImputer(strategy='mean')
df['Income'] = mean_imputer_income.fit_transform(df[['Income']])

print("\nDataFrame After Imputation (with Indicators):")
print(df)

DataFrame After Imputation (with Indicators):
   ID   Age   Income  Score  Age_missing_indicator  Income_missing_indicator
0   1  25.0  50000.0     85                      0                         0
1   2  30.0  60000.0     90                      0                         0
2   3  30.0  75000.0     78                      1                         0
3   4  35.0  68750.0     92                      0                         1
4   5  30.0  90000.0     88                      1                         0

Now, the Age and Income columns have no missing values, but the corresponding _missing_indicator columns retain the information about where the original missing values were located. Your machine learning model can potentially learn from both the imputed value and the pattern of missingness.

# SimpleImputer

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer

# Sample data with missing values
X = np.array([[1.0, 2.0, np.nan],
              [4.0, np.nan, 6.0],
              [7.0, 8.0, 9.0],
              [np.nan, 11.0, 12.0]])

print("Original Data:")
print(X)

# Initialize SimpleImputer with the 'median' strategy
imputer = SimpleImputer(strategy='median')

# Fit the imputer on the data (learns the medians of each column)
# Column 0 median: (1+4+7)/3 -> 4.0 (median of [1, 4, 7])
# Column 1 median: (2+8+11)/3 -> 8.0 (median of [2, 8, 11])
# Column 2 median: (6+9+12)/3 -> 9.0 (median of [6, 9, 12])
imputer.fit(X)

# Transform the data (fill missing values)
X_imputed = imputer.transform(X)

print("\nImputed Data (Median Strategy):")
print(X_imputed)

# We can also use fit_transform as a shortcut
imputer_mean = SimpleImputer(strategy='mean')
X_imputed_mean = imputer_mean.fit_transform(X)

print("\nImputed Data (Mean Strategy):")
print(X_imputed_mean)

In [ ]:
# Sample data again
X = np.array([[1.0, 2.0, np.nan],
              [4.0, np.nan, 6.0],
              [7.0, 8.0, 9.0],
              [np.nan, 11.0, 12.0]])

# Initialize SimpleImputer with median strategy and indicator
indicator_imputer = SimpleImputer(strategy='median', add_indicator=True)

# Fit and transform
X_imputed_indicated = indicator_imputer.fit_transform(X)

print("\nImputed Data with Missing Value Indicators:")
print(X_imputed_indicated)

# Note the shape difference
print(f"\nOriginal shape: {X.shape}")
print(f"Shape after imputation with indicator: {X_imputed_indicated.shape}")

# KNN Imputer

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler # Often needed before KNNImputer

# Sample data with missing values
data = {'FeatureA': [1, 2, np.nan, 4, 5, 6, 7, 9, 10],
        'FeatureB': [2, 4, 6, 8, 10, 11, 12, np.nan, 20],
        'FeatureC': [5, 10, 15, 20, 25, 30, 35, 40, 45]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# IMPORTANT: KNNImputer is sensitive to feature scaling
# Scale features before applying KNNImputer
scaler = MinMaxScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

# Initialize KNNImputer
# n_neighbors: Number of neighbors to use (k)
# weights: 'uniform' or 'distance'
imputer = KNNImputer(n_neighbors=3, weights='uniform')

# Fit and transform the scaled data
df_imputed_scaled = pd.DataFrame(imputer.fit_transform(df_scaled), columns=df.columns)

# Inverse transform to get data back in original scale
df_imputed = pd.DataFrame(scaler.inverse_transform(df_imputed_scaled), columns=df.columns)

print("\nDataFrame after KNN Imputation:")
print(df_imputed)

# Verify imputed values (e.g., for FeatureA, row 2)
print(f"\nImputed value for FeatureA at index 2: {df_imputed.loc[2, 'FeatureA']:.2f}")
# Verify imputed values (e.g., for FeatureB, row 7)
print(f"\nImputed value for FeatureB at index 7: {df_imputed.loc[7, 'FeatureB']:.2f}")